from . import ONE_KILOGRAM, ONE_SECOND, _ELEMENTARY_CHARGE, _ONE_METER, _ONE_COULOMB

from .derived_units import ONE_KILOELECTRONVOLT, ONE_ANGSTROM, ONE_NANOMETER_CU

ONE_COULOMB = _ONE_COULOMB
ELECTRON_MASS = 9.10938188e-31 * ONE_KILOGRAM
SPEED_OF_LIGHT = 299792458.0 * _ONE_METER / ONE_SECOND
PLANCKS_CONSTANT = 6.626068e-34 * _ONE_METER * _ONE_METER * ONE_KILOGRAM / ONE_SECOND
PLANCKS_CONSTANT_SQ = PLANCKS_CONSTANT * PLANCKS_CONSTANT
ELEC_REST_ENERGY = 510.99891 * ONE_KILOELECTRONVOLT
BOHR_RADIUS = 0.529177 * ONE_ANGSTROM
ICE_DENS = 33.5 / ONE_NANOMETER_CU
CARBON_DENS = 1e2 / ONE_NANOMETER_CU
ELEMENTARY_CHARGE = _ELEMENTARY_CHARGE
